# Generated by Django 5.1.4 on 2024-12-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='item',
            name='has_sub_items',
        ),
        migrations.RemoveField(
            model_name='list',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Complete')], default=0),
        ),
    ]
