# Generated by Django 4.2.16 on 2024-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='done',
            new_name='complete',
        ),
        migrations.AddField(
            model_name='item',
            name='has_sub_items',
            field=models.BooleanField(default=False),
        ),
    ]
