# Generated by Django 4.2.16 on 2024-12-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_done_item_complete_item_has_sub_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
